### ISSUE TITLE
show "current state"

### ISSUE THREAD

**Issue by fan1x** [BakhtinArtem/carRentCPP#10]
aspon pro admina: 
* jaka auto jsou k dispozici
* jaka auta jsou pujcena
* uzivatele a jejich penize

**Comment by fan1x** [comment]
bez tohodle to nejde rozumne otestovat... jak jsi testoval a vedel, ze je to spravne?

**Comment by BakhtinArtem** [comment]
Já jsem přímo koukal do DB tabulek, jestli správně se data ukládají

**Comment by BakhtinArtem** [comment]
pridal jsem pro admin prehled vsech aut, vsech pujcenych aut a vsech uzivatelu
