### ISSUE TITLE
It's a client-server application, should be able to run through internet

### ISSUE THREAD

**Issue by fan1x** [BakhtinArtem/carRentCPP#3]
- have you testted it? 
- you must be able configure client with an address/port/...

**Comment by BakhtinArtem** [comment]
Tohle asi jde použit, ale já jsem to netestoval

**Comment by fan1x** [comment]
no ale jak vis, ze tedy sockety funguji spravne? Jeden z duvodu, proc pouzivat sockety a server-client aplikaci je, aby to mohlo behat pres sockety. 
Je potreba to nejak otestovat....
