### ISSUE TITLE
Missing features

### ISSUE THREAD

**Issue by fan1x** [BakhtinArtem/carRentCPP#4]
This was promissed at the end of the project: 

# Car Rent Server
Client-Server application, where users can connect to a server and rent a car. Number of cars will be automatically restarted, when the server is restarted. Mutliply user are able to connect to same server and place orders simultaneously.

## Login
The server allows client to authorize using a name. The name is a unique token, using to access own profile. If a name is entered for the first time, than the new user is created, otherwise the user is logged in his profile. 

## Features
Client is able to:

- Rent a car(s) from given list
- Finish/Submit/Cancel order(s)

## User profile
Profile consist of things such as:

- Current orders
- History of orders
- Budget Remaining
- Logout option

## Start
User and Client executable files can be generating using make command.

+ things from my side
```
- detailnejsi popis te knihovny na sitovani
- Jak se pridavaji auta? IMHO by to chtelo interface jak pro uzivatele, tak pro spravce (z toho plynou nejaka podpora pro prava)
pridat podporu ukladani do souboru/DB, aby po restartu program bezel od posledniho stavu. Idealne propojit s nejakou databazi a ukladat tam, pripadne udelat vlastni soubory na odkladani.
- Jak se bude provadet autorizace? Idealne pouzit nejakou knihovna na sifrovani/autorize, pripadne hodne hezky odstinit, aby bylo jednoduche vymenit za knihovnu. 
```

**Comment by fan1x** [comment]
Na zápočet: 

```
Co je teda potřeba dodělat z funkcionality aby to stačilo na zápočet (viz specifikace)
- libovolný počet připojených klientů (neměl by to být rozdíl oproti 2)
- historie klienta (uživatel může vidět všechny své výpůjčky)
- budget/peníze
- objednávka na určitý den auta
- zrušení objednávky (může udělat jen prodejce, protože to znamená vrácení peněz; případně jinou rozumnou implementaci)

Jak si představuji funkcionalitu peněz: Každé auto má nějakou cenu na den. Klient má na svém účtu peníze. Peníze mu může dobít pouze prodejce (v reálném obchodě by uživatel dal fyzicky peníze a prodejce mu zvedne peníze na účtu). Uživatel si může zarezervovat auto, pokud na to má dost peněz - cena výpůjčky je počet dní * cena. Po provedení výpůjčky se peníze strhnou z účtu. 

Jinak, pokud si někdo vypůjčí auto, tak si ho už samozřejmě nemůže půjčit nikdo jiný na dané dny. (Je potřeba otestovat paralelní vypůjčování stejného auta více uživateli). 
```

**Comment by BakhtinArtem** [comment]
- [x] historie clienta

**Comment by BakhtinArtem** [comment]
- [x] objednavka na urcite obdobi od year-month-day do year-month-day

**Comment by BakhtinArtem** [comment]
- [x] Klient muze vratit auto kdyz dokonci je vyuzivat

- [ ] Admin muze stornovat objednavku a penize se vrateji klientovi na ucet

**Comment by BakhtinArtem** [comment]
> * [x]  Klient muze vratit auto kdyz dokonci je vyuzivat
> * [x]  Admin muze stornovat objednavku a penize se vrateji klientovi na ucet

**Comment by BakhtinArtem** [comment]
- [x] libovolny pocet uzivatelu (vyskouseno s 5 klienty na jednou)

**Comment by BakhtinArtem** [comment]
- [x] Integracni testy
