### ISSUE TITLE
Otestovat vstupy

### ISSUE THREAD

**Issue by fan1x** [BakhtinArtem/carRentCPP#6]
Vsechny vstupy musi byt osetrene vuci chybnym vstupum... napr. zadavani data, zadavani volby akce atd... Momentalne se program sekne/spadne, pri zadani spatneho vstupu

**Comment by fan1x** [comment]
Program by nemel skoncit, ale vypsat hlasku a normalne pokracovat dal, pokud to dava smysl (treba pri zadani spatneho vstupu)

**Comment by fan1x** [comment]
Not working...
```
2. Alice 5000
3. Bob 2000
4. Anna 3000
5. Peter 4000

Please enter user id to delete:
1
OK
```

**Comment by BakhtinArtem** [comment]
Ja jsem opravil vsechny + pridal chybove hlasky. Melo by to uz fungovat i pro ostatni pripady take
