### ISSUE TITLE
Uzivatele nejsou brany z config file `Users.txt`

### ISSUE THREAD

**Issue by fan1x** [BakhtinArtem/carRentCPP#7]

**Comment by BakhtinArtem** [comment]
- [ ] Pridani/mazani useru pres admin panel

**Comment by BakhtinArtem** [comment]
- [x] nastaveni portu

**Comment by BakhtinArtem** [comment]
> * [x]  Pridani/mazani useru pres admin panel

pridano

**Comment by fan1x** [comment]
Jak to, ze se clienti pripojuji na porty 62892, kdyz server bezi na portu 54000??? Clienti by se meli pripojovat pouze na port, kde bezi server (ne port per client...)
```
Server is running on port: 54000
NEW USER: t430 on port 62892 is connected
NEW USER: t430 on port 62893 is connected
```

**Comment by BakhtinArtem** [comment]
viz #11
