### ISSUE TITLE
Otestovat sockety a pridat moznost zmenit port

### ISSUE THREAD

**Issue by fan1x** [BakhtinArtem/carRentCPP#9]
Co kdyz je port obsazeny? Melo by jit nekde v configu (jako argument) nakonfigurovat, kde to ma bezet....

**Comment by BakhtinArtem** [comment]
omylem jsem napsal jiny issue viz #7

**Comment by BakhtinArtem** [comment]
viz [ports](https://github.com/BakhtinArtem/carRentCPP/blob/main/README.md#building) a [execution](https://github.com/BakhtinArtem/carRentCPP/blob/main/README.md#execution)

**Comment by fan1x** [comment]
Jak to, ze se clienti pripojuji na porty 62892, kdyz server bezi na portu 54000??? Clienti by se meli pripojovat pouze na port, kde bezi server (ne port per client...)
```
Server is running on port: 54000
NEW USER: t430 on port 62892 is connected
NEW USER: t430 on port 62893 is connected
```

**Comment by BakhtinArtem** [comment]
ne, tohle je port clientu (port ktery client pouziva pro komunkace se serverem). Clienti se pripojou na jeden port serveru, coz v danem pripade je 54000.
